---
# This role installs httpd

- name: Install http and php etc
  apt: name={{ item }} state=present
  with_items:
   - apache2

- name: apache service state
  service: name=apache2 state=started enabled=yes
