---

# httpd is handled by the base-apache role upstream
- name: Install php and git
  apt: name={{ item }} state=present
  with_items:
   - libapache2-mod-php5
   - php5-mysql
   - git

- name: Copy the code from repository
  git: repo={{ repository }} version={{ webapp_version }} dest=/var/www/html/website
